title: Team JaCKfruiT
description: A web application for uninsured/underinsured residents of Hawaii to get care.
google_analytics:
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
